name: QA - Build & Deploy
on:
  push:
    branches: [QA]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2

        with:
          host: ${{secrets.QA_SSH_HOST}}
          key: ${{secrets.QA_SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME}}

          script: |
            sudo systemctl stop front-end
            rm -r qa_project
            mkdir qa_project
            cd qa_project
            git clone -b QA https://github.com/ecoleduweb/ProjetApplicationH2024.git
            echo 'Deployment successful to QA server'
            echo 'Installing backend packages'
            sudo apt-get update -y
            sudo apt-get install -y libmariadb-dev
            python -m pip install --upgrade pip
            cd /${{ secrets.SSH_USERNAME}}/qa_project/ProjetApplicationH2024/back-end/API
            pip install -r requirements.txt
            touch .env
            echo DATABASE_TEST_URL=${{ secrets.DATABASE_TEST_URL }} >> .env
            echo DATABASE_DEV_URL=${{ secrets.DATABASE_DEV_URL }} >> .env
            echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
            echo 'Installing packages'
            cd /${{ secrets.SSH_USERNAME}}/qa_project/ProjetApplicationH2024/front-end/projet_application
            npm i
            touch .env
            echo PUBLIC_BASE_URL = ${{ secrets.FRONT_PUBLIC_URL }} >> .env
            echo HOST = ${{ secrets.FRONT_HOST }} >> .env
            echo 'Starting services'
            sudo systemctl enable front-end
            sudo systemctl start front-end
